# fly.toml app configuration file generated for newmantest on 2025-01-05T09:03:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'newmantest'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
